### ISSUE TITLE
Adding KFServing in KubeFlow UI

### ISSUE THREAD

**Issue by goswamig** [kserve/kserve#1611]
Do we have plan to add KFServing UI in KubeFlow UI or integrate it with KubeFlow UI?

**Comment by yuzisun** [comment]
@kimwnasptd It works both standalone and in Kubeflow UI right?

**Comment by kimwnasptd** [comment]
> @kimwnasptd It works both standalone and in Kubeflow UI right?

Correct, the only missing part for exposing the web app is to modify the app's ConfigMap to include a link to the app, in the sidebar. The [current manifests](https://github.com/kubeflow/kfserving/blob/master/config/web-app/istio.yaml#L14) also create a VirtualService to expose the app under the `/models` prefix.

> Do we have plan to add KFServing UI in KubeFlow UI or integrate it with KubeFlow UI?

I'll open a PR to also include the app in the KF CentralDashboard. It should not land in KF 1.3.1, since this point release will only include bug fixes, but I think it will be one of the prominent features for 1.4 :wink:

**Comment by goswamig** [comment]
Thank you @kimwnasptd  let me know if you need help in review.
