### ISSUE TITLE
Allow more fields in ServingRuntime Container spec

### ISSUE THREAD

**Issue by markwinter** [kserve/kserve#2095]
/kind feature

**Describe the solution you'd like**

It would help us have cleaner simpler InferenceServices if we could specify the ports and volumeMounts section in the ServingRuntime Container spec.

Is there a reason the ServingRuntime Container spec isn't just the k8s v1.Container Spec instead of a few select fields?

@pvaneck

**Comment by pvaneck** [comment]
I believe the limited fields are carry-over from ModelMesh, the originator of the ServingRuntime. I suppose it would make sense to   remove the limited selection of fields given your scenarios.

@njhill @yuzisun Any thoughts on replacing the [ServingRuntime container spec](https://github.com/kserve/kserve/blob/master/pkg/apis/serving/v1alpha1/servingruntime_types.go#L41) with just the v1.Container spec?

**Comment by yuzisun** [comment]
> I believe the limited fields are carry-over from ModelMesh, the originator of the ServingRuntime. I suppose it would make sense to remove the limited selection of fields given your scenarios.
> 
> @njhill @yuzisun Any thoughts on replacing the [ServingRuntime container spec](https://github.com/kserve/kserve/blob/master/pkg/apis/serving/v1alpha1/servingruntime_types.go#L41) with just the v1.Container spec?

sounds good to me, the `InferenceService` is using `v1.Container` already so it is better to be consistent.

**Comment by njhill** [comment]
I think in the model-mesh case it was primarily to keep the surface area smaller and because the idea is that the runtime container is mostly "managed" by our controller and kind of sits behind the modelmesh container in the same pod. For example the volume mounts and pre-stop hook are configured by the controller since it  handles the storage and shutdown sequencing, etc. It doesn't look like it currently sets the ports field, but it could set this based on the ports advertised by the endpoints fields in the `ServingRuntime`. I think the reason that it doesn't is that these ports are intended to be for intra-pod communication only, and that field is informational anyhow.

Having said that, I don't think it would harm to use `v1.Container`, we could override/merge/fail as appropriate if some of these other fields are set.

@markwinter I'm curious what is it that you want to use the volumeMounts / ports for in this case?

**Comment by markwinter** [comment]
@njhill 
Our model server image was hardcoded to listen on port 80 so we used the ports section to reflect that. We're updating to use `$PORT` var instead so the ports section wont be necessary.

As for volumeMounts, our model server runtime needs some shared memory.

Of course this can all be specified in the InferenceService, but I want our users to write as little yaml as possible, so the more I can specify in the ServingRuntime the better

**Comment by markwinter** [comment]
Done in https://github.com/kserve/kserve/pull/2112

Thanks @Suresh-Nakkeran
