### ISSUE TITLE
Makes KFServing supports batch inference

### ISSUE THREAD

**Issue by axelborja** [kserve/kserve#369]
/kind feature

**Describe the solution you'd like**

Makes KFServing supports batch inference. 

It could take the following form:

BatchPredict    POST    `/v1/models/<model_name>:batch_predict`
Request: {instances_path, predictions_path}
Response: {}

**Comment by ellis-bigelow** [comment]
Can you describe your usecase? This is currently identical to predict. I
expect batch predict will not be http. I'd love to hear any requirements
you have.

**Comment by axelborja** [comment]
Hello Ellis,

*Use Case*

Our use case is to request inference by batches of tens of millions of instances, and this a multitude of time a day.

The inference will probably take tens of seconds or even a few minutes.

*Triggering*

The triggering should be done on demand.

It could be event-driven. Triggered by an event, and triggering another event when done.

It could even be an HTTP request but if it is, we could not expect to get a response of completion on the triggering call. However, a second call on another route could be done to get the job status.

* Inference *

I think the logic of applying the model is quite similar than the current KFServing one. We expect to use pre/post processing and transformers.

* Parameters *

The requester should provide 2 parameters, which is the input/output file paths of the inference job: 
 - instances_path 
 - predictions_path

**Comment by cliveseldon** [comment]
One possibility would be a CRD that allows these requirements and wires things together with Knative eventing. Maybe the user can provide existing Knative source, sinks.

**Comment by yuzisun** [comment]
Looks like the use case here is batch file in and batch file out, somewhere on the pipeline we need to do micro batches since single event processing is not efficient in this case, matrix operations on batches would be much more performant especially on predictor. 

I did a bit digging looks like on gcloud Apache Beam is used for batch prediction and under kubeflow there is also a repo batch-prediction( https://cloud.google.com/ml-engine/docs/tensorflow/online-vs-batch-prediction) which uses Apache beam although seems no longer active.

So far kfserving has been targeting the use cases for online prediction, we’d love to support batch prediction but need to think about how would the architecture looks like.

These are good readings:
https://cloud.google.com/ml-engine/docs/tensorflow/online-vs-batch-prediction
https://cloud.google.com/solutions/comparing-ml-model-predictions-using-cloud-dataflow-pipelines

**Comment by wronk** [comment]
I'm also looking to do batched inference with kubeflow, so +1 for this feature and thanks @yuzisun for those resources. Our use case is running inference over very large sets (10s to 100s of millions) of satellite images. On-demand or event triggering would also be helpful for us as the frequency can vary quite a bit by project (but likely between once a week to once every 3 months).

**Comment by radcheb** [comment]
👍

**Comment by apryiomka** [comment]
As i understand, the ask is similar to Sagemaker batch transform?

**Comment by radcheb** [comment]
> As i understand, the ask is similar to Sagemaker batch transform?

Yes it's a bit similar but should be more efficient. Sagemaker batch transform is using regular inference endpoints to batch inference with HTTP as transfer protocol. It's not efficient for big datasets.

**Comment by axelborja** [comment]
Agree with @radcheb

**Comment by axelborja** [comment]
Hello guys, any news on this one ?

**Comment by andyi2it** [comment]
/close

KServe supports batching using the batcher implementation #847.
If you need any changes to the implementation please create a new issue.
