### ISSUE TITLE
E2E KFServing tests for GCP (and other platforms)

### ISSUE THREAD

**Issue by jlewi** [kserve/kserve#930]
/kind feature

Our test suite for GCP currently doesn't include any coverage for KFServing.

Here's our existing test grid:
https://k8s-testgrid.appspot.com/sig-big-data#kubeflow-gcp-blueprints-periodic-1-1&group-by-hierarchy-pattern=%5B%5Cw-%5D%2B

Do we have a python program or notebook that we could run as an E2E test? This could be something simple e.g. deploy a model and verify we can send predictions.

/cc @yuzisun

**Comment by yuzisun** [comment]
@jinchihe will you be able to work on this?
 /cc @animeshsingh

**Comment by jinchihe** [comment]
OK, I will take this asap. Thanks.

**Comment by jinchihe** [comment]
Hello @jlewi 

I took a look the problem, do you think is that enough to check the KFServing Statefulsets is ready, as other Kubeflow component done? as doing in https://github.com/kubeflow/kfctl/pull/377.

Otherwise, seems we can add the KFServing E2E pytest https://github.com/kubeflow/kfserving/blob/master/test/e2e/predictor/test_tensorflow.py
to kfctl (or can use directly)
https://github.com/kubeflow/kfctl/tree/master/py/kubeflow/kfctl/testing/pytests
And then create a tasks under `testing` repo https://github.com/kubeflow/testing/tree/master/acm-repos/kf-ci-v1/namespaces/kf-ci
And update the prow_config.yaml under gcp-blueprints repo to load that, right?

Personally I think that's OK to just check the Statefulsets status, since in this repo, we already did some E2E cases, I think we can ensure the quality.  Thanks.

**Comment by animeshsingh** [comment]
@jinchihe if you have bandwidth, adding KFServing E2E pytest to kfctl would be great, as the combination of istio and knative introduces a lot of variability in kfserving deployment, and unless we are able to push a model, its always going to remain incomplete.

also if you can syncup with @shawnzhu and @adrian555 to enable an e2e test for ibm cloud, would be great.

**Comment by jinchihe** [comment]
@animeshsingh OK, I'm doing that in https://github.com/kubeflow/kfctl/pull/377 Thanks.

**Comment by jlewi** [comment]
There are potentially two sets of tests we might want to run

1. A smoke test that just verifies that the respective K8s components to install KNative and KFServing were installed
1. An E2E test that actually tries to deploy the model and verifies it was deployed successfully
    * I think this is what @animeshsingh was talking about and what I initially filed the issue about.

I think the 2nd of these should definetely live in the KFServing repo and not kfctl. 

Ideally the first one would live in the kfserving repo as well. However, our other smoke tests along these lines currently live in kubeflow/kfctl. So if its convenient the smoke test could be added there and we could move it at some time in the future.

**Comment by jinchihe** [comment]
@jlewi Thanks. If so, I will update the https://github.com/kubeflow/kfctl/pull/377 to only check the first item (only check install and started successfully) in your comments.  For 2nd, we already have E2E tests (deploy the model and verifies it was deployed successfully) in KFServing repo.
